"""Initial Schema with StoredFile

Revision ID: ae42c29abdc6
Revises: 
Create Date: 2026-09-09 04:12:18.025365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ae42c29abdc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification',
    sa.Column('classification_id', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['classification.classification_id'], ),
    sa.PrimaryKeyConstraint('classification_id')
    )
    op.create_index(op.f('ix_classification_code'), 'classification', ['code'], unique=True)
    op.create_index('ix_classification_parent', 'classification', ['parent_id'], unique=False)
    op.create_index(op.f('ix_classification_parent_id'), 'classification', ['parent_id'], unique=False)
    op.create_table('cpse',
    sa.Column('cpse_id', sa.String(length=64), nullable=False),
    sa.Column('cpse_code', sa.String(length=20), nullable=False),
    sa.Column('cpse_name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')", name='ck_cpse_status'),
    sa.PrimaryKeyConstraint('cpse_id')
    )
    op.create_index(op.f('ix_cpse_cpse_code'), 'cpse', ['cpse_code'], unique=True)
    op.create_index('ix_cpse_sector', 'cpse', ['sector'], unique=False)
    op.create_table('matching_rule',
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logic_payload', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('model_registry',
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('task', sa.String(length=100), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('deployment_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("deployment_status IN ('ACTIVE','DEPRECATED','ARCHIVED')", name='ck_model_deployment_status'),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('model_name', 'model_version', name='uq_model_registry_name_version')
    )
    op.create_index(op.f('ix_model_registry_deployment_status'), 'model_registry', ['deployment_status'], unique=False)
    op.create_table('processing_job',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('successful', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','RUNNING','COMPLETED','FAILED','CANCELLED')", name='ck_job_status'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('ix_job_status_type', 'processing_job', ['status', 'job_type'], unique=False)
    op.create_index(op.f('ix_processing_job_job_type'), 'processing_job', ['job_type'], unique=False)
    op.create_index(op.f('ix_processing_job_status'), 'processing_job', ['status'], unique=False)
    op.create_table('prompt_registry',
    sa.Column('prompt_id', sa.String(length=64), nullable=False),
    sa.Column('task', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('prompt_id'),
    sa.UniqueConstraint('prompt_version')
    )
    op.create_index(op.f('ix_prompt_registry_is_active'), 'prompt_registry', ['is_active'], unique=False)
    op.create_index(op.f('ix_prompt_registry_task'), 'prompt_registry', ['task'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('synonym',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('expansion', sa.String(length=200), nullable=False),
    sa.Column('is_ambiguous', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term', 'expansion', name='uq_synonym_pair')
    )
    op.create_index('ix_synonym_term', 'synonym', ['term'], unique=False)
    op.create_table('uom_master',
    sa.Column('canonical_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('dimension', sa.String(length=50), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('base_multiplier', sa.Float(), nullable=True),
    sa.Column('is_base_unit', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('canonical_code')
    )
    op.create_index('ix_uom_dimension', 'uom_master', ['dimension'], unique=False)
    op.create_index('ix_uom_status', 'uom_master', ['status'], unique=False)
    op.create_table('attribute_definition',
    sa.Column('attribute_definition_id', sa.String(length=64), nullable=False),
    sa.Column('classification_id', sa.String(length=64), nullable=False),
    sa.Column('attribute_name', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['classification_id'], ['classification.classification_id'], ),
    sa.PrimaryKeyConstraint('attribute_definition_id'),
    sa.UniqueConstraint('classification_id', 'attribute_name', name='uq_attr_def_class_name')
    )
    op.create_index(op.f('ix_attribute_definition_classification_id'), 'attribute_definition', ['classification_id'], unique=False)
    op.create_table('source_material',
    sa.Column('source_material_id', sa.String(length=64), nullable=False),
    sa.Column('cpse_id', sa.String(length=64), nullable=False),
    sa.Column('legacy_material_code', sa.String(length=100), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=True),
    sa.Column('raw_uom', sa.String(length=50), nullable=True),
    sa.Column('raw_category', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('manufacturer_part_number', sa.String(length=100), nullable=True),
    sa.Column('raw_specification', sa.Text(), nullable=True),
    sa.Column('plant', sa.String(length=50), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_record_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cpse_id'], ['cpse.cpse_id'], ),
    sa.PrimaryKeyConstraint('source_material_id'),
    sa.UniqueConstraint('cpse_id', 'legacy_material_code', name='uq_cpse_legacy_code')
    )
    op.create_index('ix_source_material_cpse_legacy', 'source_material', ['cpse_id', 'legacy_material_code'], unique=False)
    op.create_index(op.f('ix_source_material_manufacturer'), 'source_material', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_source_material_manufacturer_part_number'), 'source_material', ['manufacturer_part_number'], unique=False)
    op.create_table('user_account',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role_id', sa.String(length=50), nullable=True),
    sa.Column('cpse_code', sa.String(length=20), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_retired', sa.Boolean(), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.Column('retired_by', sa.String(), nullable=True),
    sa.Column('retired_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cpse_code'], ['cpse.cpse_code'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email', name='uq_user_email')
    )
    op.create_index(op.f('ix_user_account_cpse_code'), 'user_account', ['cpse_code'], unique=False)
    op.create_index(op.f('ix_user_account_is_retired'), 'user_account', ['is_retired'], unique=False)
    op.create_index('ix_user_cpse_role', 'user_account', ['cpse_code', 'role_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('actor_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('rules_version', sa.String(length=50), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('critical_rule',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('classification_code', sa.String(length=100), nullable=False),
    sa.Column('attribute', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('conflict_behavior', sa.String(length=50), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("conflict_behavior IN ('BLOCK_EQUIVALENCE','REQUIRE_REVIEW','FLAG_ONLY')", name='ck_critical_rule_behavior'),
    sa.CheckConstraint("severity IN ('CRITICAL','HIGH','MEDIUM','LOW')", name='ck_critical_rule_severity'),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_critical_rule_cat_attr', 'critical_rule', ['classification_code', 'attribute'], unique=False)
    op.create_index(op.f('ix_critical_rule_classification_code'), 'critical_rule', ['classification_code'], unique=False)
    op.create_index(op.f('ix_critical_rule_is_latest'), 'critical_rule', ['is_latest'], unique=False)
    op.create_index('ix_critical_rule_latest', 'critical_rule', ['is_latest'], unique=False)
    op.create_table('file_upload',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('cpse_code', sa.String(length=20), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=50), nullable=True),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cpse_code'], ['cpse.cpse_code'], ),
    sa.ForeignKeyConstraint(['job_id'], ['processing_job.job_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_upload_cpse', 'file_upload', ['cpse_code'], unique=False)
    op.create_index(op.f('ix_file_upload_cpse_code'), 'file_upload', ['cpse_code'], unique=False)
    op.create_index(op.f('ix_file_upload_job_id'), 'file_upload', ['job_id'], unique=False)
    op.create_table('global_matching_config',
    sa.Column('config_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('weight_semantic', sa.Float(), nullable=True),
    sa.Column('weight_attribute', sa.Float(), nullable=True),
    sa.Column('weight_manufacturer', sa.Float(), nullable=True),
    sa.Column('weight_mpn', sa.Float(), nullable=True),
    sa.Column('threshold_exact_duplicate', sa.Float(), nullable=True),
    sa.Column('threshold_near_duplicate', sa.Float(), nullable=True),
    sa.Column('threshold_functionally_equivalent', sa.Float(), nullable=True),
    sa.Column('threshold_related', sa.Float(), nullable=True),
    sa.Column('penalty_missing_attribute', sa.Float(), nullable=True),
    sa.Column('penalty_critical_conflict', sa.Float(), nullable=True),
    sa.Column('auto_approve_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_approve_threshold', sa.Float(), nullable=True),
    sa.Column('auto_approve_max_risk_level', sa.String(length=20), nullable=True),
    sa.Column('high_risk_categories', sa.JSON(), nullable=True),
    sa.Column('medium_risk_categories', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("auto_approve_max_risk_level IN ('LOW','MEDIUM','HIGH','CRITICAL')", name='ck_gmc_risk_level'),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_index('ix_global_config_latest', 'global_matching_config', ['is_latest'], unique=False)
    op.create_index(op.f('ix_global_matching_config_is_latest'), 'global_matching_config', ['is_latest'], unique=False)
    op.create_table('ground_truth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_material_id_a', sa.String(length=64), nullable=True),
    sa.Column('source_material_id_b', sa.String(length=64), nullable=True),
    sa.Column('ground_truth_label', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('annotator_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("ground_truth_label IN ('MATCH','NO_MATCH','CONFLICT','NEAR_DUPLICATE','FUNCTIONAL_EQUIV')", name='ck_gt_label'),
    sa.ForeignKeyConstraint(['source_material_id_a'], ['source_material.source_material_id'], ),
    sa.ForeignKeyConstraint(['source_material_id_b'], ['source_material.source_material_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_material_id_a', 'source_material_id_b', name='uq_ground_truth_pair')
    )
    op.create_index(op.f('ix_ground_truth_source_material_id_a'), 'ground_truth', ['source_material_id_a'], unique=False)
    op.create_index(op.f('ix_ground_truth_source_material_id_b'), 'ground_truth', ['source_material_id_b'], unique=False)
    op.create_table('migration_batch',
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','VALIDATED','APPROVED','READY','EXECUTED','ROLLED_BACK','FAILED')", name='ck_migration_batch_status'),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_migration_batch_status'), 'migration_batch', ['status'], unique=False)
    op.create_table('national_material',
    sa.Column('national_material_id', sa.String(length=64), nullable=False),
    sa.Column('national_material_code', sa.String(length=50), nullable=False),
    sa.Column('canonical_description', sa.Text(), nullable=False),
    sa.Column('classification_id', sa.String(length=64), nullable=True),
    sa.Column('canonical_uom', sa.String(length=20), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_retired', sa.Boolean(), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.Column('retired_by', sa.String(), nullable=True),
    sa.Column('retired_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('PROVISIONAL','UNDER_REVIEW','ACTIVE','SUPERSEDED','RETIRED','REJECTED')", name='ck_national_status'),
    sa.ForeignKeyConstraint(['canonical_uom'], ['uom_master.canonical_code'], ),
    sa.ForeignKeyConstraint(['classification_id'], ['classification.classification_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('national_material_id')
    )
    op.create_index(op.f('ix_national_material_canonical_uom'), 'national_material', ['canonical_uom'], unique=False)
    op.create_index('ix_national_material_category', 'national_material', ['classification_id'], unique=False)
    op.create_index(op.f('ix_national_material_classification_id'), 'national_material', ['classification_id'], unique=False)
    op.create_index(op.f('ix_national_material_is_retired'), 'national_material', ['is_retired'], unique=False)
    op.create_index(op.f('ix_national_material_national_material_code'), 'national_material', ['national_material_code'], unique=True)
    op.create_index('ix_national_material_status', 'national_material', ['status'], unique=False)
    op.create_table('normalized_material',
    sa.Column('normalized_material_id', sa.String(length=64), nullable=False),
    sa.Column('source_material_id', sa.String(length=64), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=True),
    sa.Column('normalized_description', sa.Text(), nullable=True),
    sa.Column('canonical_uom', sa.String(length=20), nullable=True),
    sa.Column('category_code', sa.String(length=50), nullable=True),
    sa.Column('normalized_manufacturer', sa.String(length=200), nullable=True),
    sa.Column('normalized_mpn', sa.String(length=200), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('normalization_version', sa.String(length=50), nullable=True),
    sa.Column('normalization_method', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_uom'], ['uom_master.canonical_code'], ),
    sa.ForeignKeyConstraint(['category_code'], ['classification.code'], ),
    sa.ForeignKeyConstraint(['source_material_id'], ['source_material.source_material_id'], ),
    sa.PrimaryKeyConstraint('normalized_material_id'),
    sa.UniqueConstraint('source_material_id', 'normalization_version', name='uq_normalized_source_version')
    )
    op.create_index('ix_normalized_category', 'normalized_material', ['category_code'], unique=False)
    op.create_index('ix_normalized_embedding_hnsw', 'normalized_material', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_normalized_manufacturer', 'normalized_material', ['normalized_manufacturer'], unique=False)
    op.create_index(op.f('ix_normalized_material_canonical_uom'), 'normalized_material', ['canonical_uom'], unique=False)
    op.create_index(op.f('ix_normalized_material_category_code'), 'normalized_material', ['category_code'], unique=False)
    op.create_index(op.f('ix_normalized_material_normalized_manufacturer'), 'normalized_material', ['normalized_manufacturer'], unique=False)
    op.create_index(op.f('ix_normalized_material_source_material_id'), 'normalized_material', ['source_material_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_index('ix_notification_user_unread', 'notification', ['user_id', 'is_read'], unique=False)
    op.create_table('procurement_record',
    sa.Column('procurement_id', sa.String(length=64), nullable=False),
    sa.Column('source_material_id', sa.String(length=64), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_spend', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('procurement_date', sa.DateTime(), nullable=True),
    sa.Column('plant', sa.String(length=50), nullable=True),
    sa.Column('purchase_order', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_material_id'], ['source_material.source_material_id'], ),
    sa.PrimaryKeyConstraint('procurement_id')
    )
    op.create_index('ix_proc_source_date', 'procurement_record', ['source_material_id', 'procurement_date'], unique=False)
    op.create_index('ix_proc_supplier', 'procurement_record', ['supplier'], unique=False)
    op.create_index(op.f('ix_procurement_record_procurement_date'), 'procurement_record', ['procurement_date'], unique=False)
    op.create_index(op.f('ix_procurement_record_source_material_id'), 'procurement_record', ['source_material_id'], unique=False)
    op.create_index(op.f('ix_procurement_record_supplier'), 'procurement_record', ['supplier'], unique=False)
    op.create_index(op.f('ix_procurement_record_total_spend'), 'procurement_record', ['total_spend'], unique=False)
    op.create_table('stored_file',
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('file_hash', sa.String(length=256), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_stored_file_storage_key'), 'stored_file', ['storage_key'], unique=True)
    op.create_table('data_quality_metrics',
    sa.Column('metric_id', sa.String(length=64), nullable=False),
    sa.Column('material_id', sa.String(length=64), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('uniqueness_score', sa.Float(), nullable=True),
    sa.Column('validity_score', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('standardization_score', sa.Float(), nullable=True),
    sa.Column('attribute_coverage', sa.Float(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['normalized_material.normalized_material_id'], ),
    sa.PrimaryKeyConstraint('metric_id'),
    sa.UniqueConstraint('material_id')
    )
    op.create_table('match_result',
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('material_a_id', sa.String(length=64), nullable=True),
    sa.Column('material_b_id', sa.String(length=64), nullable=True),
    sa.Column('semantic_score', sa.Float(), nullable=True),
    sa.Column('attribute_score', sa.Float(), nullable=True),
    sa.Column('rule_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('match_type', sa.String(length=50), nullable=True),
    sa.Column('positive_evidence', sa.JSON(), nullable=True),
    sa.Column('negative_evidence', sa.JSON(), nullable=True),
    sa.Column('conflicts', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('rules_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('attribute_score >= 0 AND attribute_score <= 1', name='ck_match_attribute_score'),
    sa.CheckConstraint('final_score >= 0 AND final_score <= 1', name='ck_match_final_score'),
    sa.CheckConstraint('rule_score >= 0 AND rule_score <= 1', name='ck_match_rule_score'),
    sa.CheckConstraint('semantic_score >= 0 AND semantic_score <= 1', name='ck_match_semantic_score'),
    sa.ForeignKeyConstraint(['material_a_id'], ['normalized_material.normalized_material_id'], ),
    sa.ForeignKeyConstraint(['material_b_id'], ['national_material.national_material_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index('ix_match_result_final_score', 'match_result', ['material_a_id', 'final_score'], unique=False)
    op.create_index(op.f('ix_match_result_material_a_id'), 'match_result', ['material_a_id'], unique=False)
    op.create_index(op.f('ix_match_result_material_b_id'), 'match_result', ['material_b_id'], unique=False)
    op.create_table('material_attribute',
    sa.Column('material_attribute_id', sa.String(length=64), nullable=False),
    sa.Column('normalized_material_id', sa.String(length=64), nullable=True),
    sa.Column('national_material_id', sa.String(length=64), nullable=True),
    sa.Column('attribute_name', sa.String(length=100), nullable=False),
    sa.Column('original_value', sa.String(length=500), nullable=True),
    sa.Column('normalized_value', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('source_span', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(normalized_material_id IS NOT NULL AND national_material_id IS NULL) OR (normalized_material_id IS NULL AND national_material_id IS NOT NULL)', name='ck_mat_attr_reference'),
    sa.ForeignKeyConstraint(['national_material_id'], ['national_material.national_material_id'], ),
    sa.ForeignKeyConstraint(['normalized_material_id'], ['normalized_material.normalized_material_id'], ),
    sa.PrimaryKeyConstraint('material_attribute_id')
    )
    op.create_index('ix_mat_attr_nat_name', 'material_attribute', ['national_material_id', 'attribute_name'], unique=False)
    op.create_index('ix_mat_attr_norm_name', 'material_attribute', ['normalized_material_id', 'attribute_name'], unique=False)
    op.create_index(op.f('ix_material_attribute_national_material_id'), 'material_attribute', ['national_material_id'], unique=False)
    op.create_index(op.f('ix_material_attribute_normalized_material_id'), 'material_attribute', ['normalized_material_id'], unique=False)
    op.create_table('material_mapping',
    sa.Column('mapping_id', sa.String(length=64), nullable=False),
    sa.Column('source_material_id', sa.String(length=64), nullable=False),
    sa.Column('national_material_id', sa.String(length=64), nullable=False),
    sa.Column('mapping_type', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('is_ai_suggested', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("mapping_type IN ('EXACT_DUPLICATE','NEAR_DUPLICATE','FUNCTIONALLY_EQUIVALENT','LEGACY_MAPPING')", name='ck_mapping_type'),
    sa.CheckConstraint("status IN ('PENDING','APPROVED','REJECTED','ENGINEERING_REVIEW')", name='ck_mapping_status'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_confidence_range'),
    sa.ForeignKeyConstraint(['approved_by'], ['user_account.user_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.user_id'], ),
    sa.ForeignKeyConstraint(['national_material_id'], ['national_material.national_material_id'], ),
    sa.ForeignKeyConstraint(['source_material_id'], ['source_material.source_material_id'], ),
    sa.PrimaryKeyConstraint('mapping_id'),
    sa.UniqueConstraint('source_material_id', 'national_material_id', name='uq_mapping_source_national')
    )
    op.create_index('ix_mapping_national_confidence', 'material_mapping', ['national_material_id', 'confidence'], unique=False)
    op.create_index(op.f('ix_material_mapping_national_material_id'), 'material_mapping', ['national_material_id'], unique=False)
    op.create_index(op.f('ix_material_mapping_source_material_id'), 'material_mapping', ['source_material_id'], unique=False)
    op.create_table('approval',
    sa.Column('approval_id', sa.String(length=64), nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=True),
    sa.Column('reviewer_id', sa.String(length=50), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('review_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("decision IN ('APPROVED','REJECTED','ESCALATED')", name='ck_approval_decision'),
    sa.ForeignKeyConstraint(['match_id'], ['match_result.match_id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index(op.f('ix_approval_match_id'), 'approval', ['match_id'], unique=False)
    op.create_index('ix_approval_status', 'approval', ['decision'], unique=False)
    op.create_table('feedback_event',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('reviewer_id', sa.String(length=50), nullable=True),
    sa.Column('match_id', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('ai_match_type', sa.String(length=50), nullable=True),
    sa.Column('ai_final_score', sa.Float(), nullable=True),
    sa.Column('ai_risk_level', sa.String(length=20), nullable=True),
    sa.Column('ai_recommendation', sa.String(length=50), nullable=True),
    sa.Column('ai_model_version', sa.String(length=50), nullable=True),
    sa.Column('ai_prompt_version', sa.String(length=50), nullable=True),
    sa.Column('ai_rules_version', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('human_decision', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('corrected_attributes', sa.JSON(), nullable=True),
    sa.Column('category_code', sa.String(length=100), nullable=True),
    sa.Column('source_material_id', sa.String(length=64), nullable=True),
    sa.Column('is_disagreement', sa.Boolean(), nullable=True),
    sa.Column('feedback_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("event_type IN ('APPROVED','REJECTED','ENGINEERING_REVIEW','ATTRIBUTE_CORRECTED')", name='ck_feedback_event_type'),
    sa.ForeignKeyConstraint(['match_id'], ['match_result.match_id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user_account.user_id'], ),
    sa.ForeignKeyConstraint(['source_material_id'], ['source_material.source_material_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_feedback_disagreement', 'feedback_event', ['is_disagreement'], unique=False)
    op.create_index('ix_feedback_event_category', 'feedback_event', ['category_code', 'event_type'], unique=False)
    op.create_index(op.f('ix_feedback_event_category_code'), 'feedback_event', ['category_code'], unique=False)
    op.create_index(op.f('ix_feedback_event_event_type'), 'feedback_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_feedback_event_human_decision'), 'feedback_event', ['human_decision'], unique=False)
    op.create_index(op.f('ix_feedback_event_is_disagreement'), 'feedback_event', ['is_disagreement'], unique=False)
    op.create_index(op.f('ix_feedback_event_match_id'), 'feedback_event', ['match_id'], unique=False)
    op.create_index(op.f('ix_feedback_event_target_id'), 'feedback_event', ['target_id'], unique=False)
    op.create_index(op.f('ix_feedback_event_target_type'), 'feedback_event', ['target_type'], unique=False)
    op.create_index('ix_feedback_target', 'feedback_event', ['target_type', 'target_id'], unique=False)
    op.create_table('migration_record',
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('legacy_code', sa.String(length=100), nullable=False),
    sa.Column('national_code', sa.String(length=50), nullable=False),
    sa.Column('mapping_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('operator_id', sa.String(length=50), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT','VALIDATED','APPROVED','READY','EXECUTED','ROLLED_BACK','FAILED')", name='ck_migration_record_status'),
    sa.ForeignKeyConstraint(['batch_id'], ['migration_batch.batch_id'], ),
    sa.ForeignKeyConstraint(['mapping_id'], ['material_mapping.mapping_id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('batch_id', 'legacy_code', name='uq_migration_batch_legacy')
    )
    op.create_index(op.f('ix_migration_record_batch_id'), 'migration_record', ['batch_id'], unique=False)
    op.create_index(op.f('ix_migration_record_legacy_code'), 'migration_record', ['legacy_code'], unique=False)
    op.create_index(op.f('ix_migration_record_national_code'), 'migration_record', ['national_code'], unique=False)
    op.create_index(op.f('ix_migration_record_status'), 'migration_record', ['status'], unique=False)
    op.create_table('retraining_candidate',
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('nominated_by', sa.String(length=64), nullable=True),
    sa.Column('nomination_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','APPROVED_FOR_TRAINING','EXCLUDED')", name='ck_retrain_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['user_account.user_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['feedback_event.event_id'], ),
    sa.ForeignKeyConstraint(['nominated_by'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_index('ix_retrain_candidate_status', 'retraining_candidate', ['status'], unique=False)
    op.create_index(op.f('ix_retraining_candidate_event_id'), 'retraining_candidate', ['event_id'], unique=False)
    op.create_index(op.f('ix_retraining_candidate_status'), 'retraining_candidate', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retraining_candidate_status'), table_name='retraining_candidate')
    op.drop_index(op.f('ix_retraining_candidate_event_id'), table_name='retraining_candidate')
    op.drop_index('ix_retrain_candidate_status', table_name='retraining_candidate')
    op.drop_table('retraining_candidate')
    op.drop_index(op.f('ix_migration_record_status'), table_name='migration_record')
    op.drop_index(op.f('ix_migration_record_national_code'), table_name='migration_record')
    op.drop_index(op.f('ix_migration_record_legacy_code'), table_name='migration_record')
    op.drop_index(op.f('ix_migration_record_batch_id'), table_name='migration_record')
    op.drop_table('migration_record')
    op.drop_index('ix_feedback_target', table_name='feedback_event')
    op.drop_index(op.f('ix_feedback_event_target_type'), table_name='feedback_event')
    op.drop_index(op.f('ix_feedback_event_target_id'), table_name='feedback_event')
    op.drop_index(op.f('ix_feedback_event_match_id'), table_name='feedback_event')
    op.drop_index(op.f('ix_feedback_event_is_disagreement'), table_name='feedback_event')
    op.drop_index(op.f('ix_feedback_event_human_decision'), table_name='feedback_event')
    op.drop_index(op.f('ix_feedback_event_event_type'), table_name='feedback_event')
    op.drop_index(op.f('ix_feedback_event_category_code'), table_name='feedback_event')
    op.drop_index('ix_feedback_event_category', table_name='feedback_event')
    op.drop_index('ix_feedback_disagreement', table_name='feedback_event')
    op.drop_table('feedback_event')
    op.drop_index('ix_approval_status', table_name='approval')
    op.drop_index(op.f('ix_approval_match_id'), table_name='approval')
    op.drop_table('approval')
    op.drop_index(op.f('ix_material_mapping_source_material_id'), table_name='material_mapping')
    op.drop_index(op.f('ix_material_mapping_national_material_id'), table_name='material_mapping')
    op.drop_index('ix_mapping_national_confidence', table_name='material_mapping')
    op.drop_table('material_mapping')
    op.drop_index(op.f('ix_material_attribute_normalized_material_id'), table_name='material_attribute')
    op.drop_index(op.f('ix_material_attribute_national_material_id'), table_name='material_attribute')
    op.drop_index('ix_mat_attr_norm_name', table_name='material_attribute')
    op.drop_index('ix_mat_attr_nat_name', table_name='material_attribute')
    op.drop_table('material_attribute')
    op.drop_index(op.f('ix_match_result_material_b_id'), table_name='match_result')
    op.drop_index(op.f('ix_match_result_material_a_id'), table_name='match_result')
    op.drop_index('ix_match_result_final_score', table_name='match_result')
    op.drop_table('match_result')
    op.drop_table('data_quality_metrics')
    op.drop_index(op.f('ix_stored_file_storage_key'), table_name='stored_file')
    op.drop_table('stored_file')
    op.drop_index(op.f('ix_procurement_record_total_spend'), table_name='procurement_record')
    op.drop_index(op.f('ix_procurement_record_supplier'), table_name='procurement_record')
    op.drop_index(op.f('ix_procurement_record_source_material_id'), table_name='procurement_record')
    op.drop_index(op.f('ix_procurement_record_procurement_date'), table_name='procurement_record')
    op.drop_index('ix_proc_supplier', table_name='procurement_record')
    op.drop_index('ix_proc_source_date', table_name='procurement_record')
    op.drop_table('procurement_record')
    op.drop_index('ix_notification_user_unread', table_name='notification')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_is_read'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_normalized_material_source_material_id'), table_name='normalized_material')
    op.drop_index(op.f('ix_normalized_material_normalized_manufacturer'), table_name='normalized_material')
    op.drop_index(op.f('ix_normalized_material_category_code'), table_name='normalized_material')
    op.drop_index(op.f('ix_normalized_material_canonical_uom'), table_name='normalized_material')
    op.drop_index('ix_normalized_manufacturer', table_name='normalized_material')
    op.drop_index('ix_normalized_embedding_hnsw', table_name='normalized_material', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_normalized_category', table_name='normalized_material')
    op.drop_table('normalized_material')
    op.drop_index('ix_national_material_status', table_name='national_material')
    op.drop_index(op.f('ix_national_material_national_material_code'), table_name='national_material')
    op.drop_index(op.f('ix_national_material_is_retired'), table_name='national_material')
    op.drop_index(op.f('ix_national_material_classification_id'), table_name='national_material')
    op.drop_index('ix_national_material_category', table_name='national_material')
    op.drop_index(op.f('ix_national_material_canonical_uom'), table_name='national_material')
    op.drop_table('national_material')
    op.drop_index(op.f('ix_migration_batch_status'), table_name='migration_batch')
    op.drop_table('migration_batch')
    op.drop_index(op.f('ix_ground_truth_source_material_id_b'), table_name='ground_truth')
    op.drop_index(op.f('ix_ground_truth_source_material_id_a'), table_name='ground_truth')
    op.drop_table('ground_truth')
    op.drop_index(op.f('ix_global_matching_config_is_latest'), table_name='global_matching_config')
    op.drop_index('ix_global_config_latest', table_name='global_matching_config')
    op.drop_table('global_matching_config')
    op.drop_index(op.f('ix_file_upload_job_id'), table_name='file_upload')
    op.drop_index(op.f('ix_file_upload_cpse_code'), table_name='file_upload')
    op.drop_index('ix_file_upload_cpse', table_name='file_upload')
    op.drop_table('file_upload')
    op.drop_index('ix_critical_rule_latest', table_name='critical_rule')
    op.drop_index(op.f('ix_critical_rule_is_latest'), table_name='critical_rule')
    op.drop_index(op.f('ix_critical_rule_classification_code'), table_name='critical_rule')
    op.drop_index('ix_critical_rule_cat_attr', table_name='critical_rule')
    op.drop_table('critical_rule')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_user_cpse_role', table_name='user_account')
    op.drop_index(op.f('ix_user_account_is_retired'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_cpse_code'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_index(op.f('ix_source_material_manufacturer_part_number'), table_name='source_material')
    op.drop_index(op.f('ix_source_material_manufacturer'), table_name='source_material')
    op.drop_index('ix_source_material_cpse_legacy', table_name='source_material')
    op.drop_table('source_material')
    op.drop_index(op.f('ix_attribute_definition_classification_id'), table_name='attribute_definition')
    op.drop_table('attribute_definition')
    op.drop_index('ix_uom_status', table_name='uom_master')
    op.drop_index('ix_uom_dimension', table_name='uom_master')
    op.drop_table('uom_master')
    op.drop_index('ix_synonym_term', table_name='synonym')
    op.drop_table('synonym')
    op.drop_table('role')
    op.drop_index(op.f('ix_prompt_registry_task'), table_name='prompt_registry')
    op.drop_index(op.f('ix_prompt_registry_is_active'), table_name='prompt_registry')
    op.drop_table('prompt_registry')
    op.drop_index(op.f('ix_processing_job_status'), table_name='processing_job')
    op.drop_index(op.f('ix_processing_job_job_type'), table_name='processing_job')
    op.drop_index('ix_job_status_type', table_name='processing_job')
    op.drop_table('processing_job')
    op.drop_index(op.f('ix_model_registry_deployment_status'), table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_table('matching_rule')
    op.drop_index('ix_cpse_sector', table_name='cpse')
    op.drop_index(op.f('ix_cpse_cpse_code'), table_name='cpse')
    op.drop_table('cpse')
    op.drop_index(op.f('ix_classification_parent_id'), table_name='classification')
    op.drop_index('ix_classification_parent', table_name='classification')
    op.drop_index(op.f('ix_classification_code'), table_name='classification')
    op.drop_table('classification')
    # ### end Alembic commands ###
